In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
data_path = "./data/"
train_df = pd.read_csv(data_path+'train.csv')
test_df = pd.read_csv(data_path+'test.csv')

In [48]:
 class DataLoader(object):
    def __init__(self):
        super(DataLoader, self).__init__()
    
    def readData(self, file_path):
        train_df = pd.read_csv(file_path+"train.csv")
        test_df = pd.read_csv(file_path+"test.csv")
        self.train_data = train_df[train_df.columns.values[1:]].values
        self.train_data_label = self.toOneHot(train_df["label"].values)
        self.test_data = test_df.values
    
    def toOneHot(self, labels):
        onehot_label = []
        for label in labels:
            tmp = np.zeros(10)
            tmp[label] = 1
            onehot_label.append(tmp)
        return np.asarray(onehot_label)
    
    def getTrainData(self):
        return self.train_data
    
    def getTrainDataLabel(self):
        return self.train_data_label
    
    def getTestData(self):
        return self.test_data


In [50]:
dataloader = DataLoader()
dataloader.readData(data_path)
dataloader.getTrainDataLabel()[1]

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [52]:
len(labels)

42000

In [34]:
c=np.array([[2,1,4]])
a=np.array([[1,2,3]])
b=np.array([[3,4,5]])
d=np.concatenate((a,b,c))
print d

[[1 2 3]
 [3 4 5]
 [2 1 4]]


In [36]:
a=np.array([1,[2,3],2])

ValueError: setting an array element with a sequence.

In [51]:
class CNN(object):
    def __init__(self):
        super(CNN, self).__init__()
        dataloader = DataLoader()
        dataloader.readData(file_path)
        self.train_data = dataloader.getTrainData()
        self.train_data_label = dataloader.getTrainDataLabel()
        self.test_data = dataloader.getTestData()

        self.loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=train_data_label, logits=layer3.output()))
        self.train_step = tf.train.AdamOptimizer(0.003).minimize(loss)

        correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(layer3.output(), 1))
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

        self.x_data = tf.placeholder(tf.float32, shape = [None, pic_dim])
        self.x_label = tf.placeholder(tf.float32, shape = [None, 10])

    def showStatus(self):
        print "step: "+str(self.step)+", loss:"++", accuracy:"

In [54]:
k=(np.random.sample(10)*42000).astype(int)

In [55]:
labels[k]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])